# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1680a4e324224b8ea27daa60cf28322b41f38bc49e087f7ff14caac4ed6df55df6faabfdb3b68ba81134f49f9f12e8ac23f17db04c327d051360e6f867defbea

test:
  secret_key_base: ed75c1cc5cf4bdcbf1803c3ee23074a4389b2bb3c869413b8f306d78012eedad3314c6554c1ed4d8cc8d8237ccb85c20f6a56321bcbb2101a0b6e141a7fc1ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
